name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Deploy to gh-pages
      env:
        NODE_ENV: production
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        npm run build && npx gh-pages -d dist -t true -b gh-pages --dotfiles --message "Deploy to gh-pages [skip ci]"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}